# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsimage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='picture/')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('location', models.ManyToManyField(blank=True, to='newsimage.Location')),
                ('tags', models.ManyToManyField(blank=True, to='newsimage.tags')),
            ],
        ),
    ]
