# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsimage', '0003_auto_20180926_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='newsimage.Location'),
        ),
    ]
