# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsimage', '0004_auto_20180926_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
