# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsimage', '0005_auto_20180926_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
